### ISSUE TITLE
Network Request send by websdk missing with few important fields

### ISSUE THREAD

**Issue by mohlogan** [ibm-bluemix-mobile-services/bms-clientsdk-web-analytics#10]
NetworkRequest missing with following entries:
    responseCode as 0
    url is missing
    requestMethod is missing

Sample NetworkRequest Entry in ES as follows:

  ```
{
    "_index": "authorized__timedraw__2017",
    "_type": "NetworkTransaction",
    "_id": "7a69c0f7-fac9-4ecd-8185-d36da635fd59",
    "_version": 3,
    "_score": null,
    "_source": {
        "appVersion": "latest",
        "appName": "com.ibm.mfpstarterweb",
        "deviceOS": "web",
        "deviceOSversion": "MacIntel",
        "deviceID": "f0143f40-5fb3-cd59-ac8f-3cbfa6f29eb5",
        "appVersionCode": "laest",
        "inboundTimestamp": 1507537760326,
        "responseCode": 0,
        "bytesReceived": 0,
        "outboundTimestamp": 1507537760131,
        "roundTripTime": 195,
        "appID": "com.ibm.mfpstarterweb",
        "deviceModel": "Firefox",
        "deviceBrand": "5.0 (Macintosh)",
        "timestamp": 1507537760326,
        "trackingID": "7a69c0f7-fac9-4ecd-8185-d36da635fd59"
    },
    "sort": [
        "com.ibm.mfpstarterweb"
    ]

} 
```

**Comment by krishnendusaha** [comment]
The issue seems to be fixed ,the ES entry for NetworkTransaction looks like this ,

{
      "_index" : "e31b1a0d-18c7-48bb-a376-39983affd262__timedraw__2017",
      "_type" : "NetworkTransaction",
      "_id" : "339bd185-0ea1-41b6-9ba8-ef2a967b2d59",
      "_score" : 1.0,
      "_source" : {
        "appVersion" : "latest",
        "deviceOS" : "web",
        "appName" : "com.ibm.mfpstarterweb",
        "requestMethod" : "POST",
        "deviceOSversion" : "MacIntel",
        "deviceID" : "4207f3d5-be4f-d9d9-306e-48bc22251ecf",
        "appVersionCode" : "latest",
        "inboundTimestamp" : 1508932945941,
        "responseCode" : 201,
        "bytesReceived" : 0,
        "outboundTimestamp" : 1508932945275,
        "resourceURL" : "https://mobile-analytics-dashboard.ng.bluemix.net/analytics-service/rest/data/events/clientlogs/",
        "roundTripTime" : 666,
        "appID" : "com.ibm.mfpstarterweb",
        "deviceModel" : "Chrome",
        "deviceBrand" : "5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/61.0.3163.100 Safari/537.36",
        "timestamp" : 1508932945942,
        "trackingID" : "339bd185-0ea1-41b6-9ba8-ef2a967b2d59"
      }
    }
